### ISSUE TITLE
Add new features to VS examples and GitBook.

### ISSUE THREAD

**Issue by goock** [coreweave/kubernetes-cloud#24]
There are new features of VitrtualServer.

## Ref

- [x] - https://github.com/coreweave/virtual-server-operator/pull/35
- [x] - https://github.com/coreweave/virtual-server-operator/pull/33
- https://github.com/coreweave/kubernetes-cloud/pull/28

## TODO
- [x] - example Go ssh
- [x] - example Go cloudinit
- [x] - example Node.js ssh
- [x] - example Node.js cloudinit
- [x] - example Python ssh
- [x] - example Python cloudinit
- [x] - example kubectl ssh
- [x] - example kubectl cloudinit
- [x] - GitBook ssh
- [x] - GitBook cloudinit

**Comment by salanki** [comment]
The gitbook stuff, for doing it via kubectl and describing what it does and limitations is much more important than updating code examples. Code examples doesn't have to showcase every feature.

**Comment by goock** [comment]
All PRs and GitBook are checked with Yitzy and merged.
